# Conexao com o Banco de Dados no Supabase
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.lvolxvxubzwrouzfpiav
spring.datasource.password=Kevintav2026@

# Configuracoes do Driver e Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true